hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/practice_db
hibernate.connection.username=postgres
hibernate.connection.password=Postgres123

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

hibernate.hbm2ddl.auto=update